package hdphoto.galleryimages.gelleryalbum.Images_android.Ibex_CollageModule.Luxgen_ShapeLayout;

import android.graphics.PointF;
import java.util.ArrayList;


public class Rabbit_ClgShape6 extends Spyker_CollageShapeUtils {
    public static int shapeCount = 6;

    public Rabbit_ClgShape6(int i, int i2) {
        this.collageLayoutList = new ArrayList();
        ArrayList arrayList = new ArrayList();
        float f = i;
        float f2 = f * 0.0f;
        float f3 = i2;
        float f4 = f3 * 0.6666667f;
        float f5 = f * 0.3333333f;
        float f6 = 0.0f * f3;
        arrayList.add(new PointF[]{new PointF(f2, f4), new PointF(f5, f4), new PointF(f5, f6), new PointF(f2, f6)});
        float f7 = f3 * 1.0f;
        arrayList.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f5, f4), new PointF(f5, f7)});
        float f8 = 0.6666667f * f;
        arrayList.add(new PointF[]{new PointF(f5, f7), new PointF(f8, f7), new PointF(f8, f4), new PointF(f5, f4)});
        float f9 = f * 1.0f;
        arrayList.add(new PointF[]{new PointF(f8, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f8, f4)});
        float f10 = 0.3333333f * f3;
        arrayList.add(new PointF[]{new PointF(f5, f10), new PointF(f9, f10), new PointF(f9, f4), new PointF(f5, f4)});
        arrayList.add(new PointF[]{new PointF(f9, f10), new PointF(f9, f6), new PointF(f5, f6), new PointF(f5, f10)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList));
        ArrayList arrayList2 = new ArrayList();
        arrayList2.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f8, f4), new PointF(f8, f7)});
        arrayList2.add(new PointF[]{new PointF(f8, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f8, f4)});
        float f11 = f * 0.5f;
        arrayList2.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f10), new PointF(f11, f10), new PointF(f11, f4)});
        arrayList2.add(new PointF[]{new PointF(f11, f10), new PointF(f9, f10), new PointF(f9, f4), new PointF(f11, f4)});
        arrayList2.add(new PointF[]{new PointF(f2, f10), new PointF(f2, f6), new PointF(f5, f6), new PointF(f5, f10)});
        arrayList2.add(new PointF[]{new PointF(f9, f6), new PointF(f5, f6), new PointF(f5, f10), new PointF(f9, f10)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList2));
        ArrayList arrayList3 = new ArrayList();
        arrayList3.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f5, f4), new PointF(f5, f7)});
        arrayList3.add(new PointF[]{new PointF(f5, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f5, f4)});
        arrayList3.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f10), new PointF(f11, f10), new PointF(f11, f4)});
        arrayList3.add(new PointF[]{new PointF(f11, f10), new PointF(f9, f10), new PointF(f9, f4), new PointF(f11, f4)});
        arrayList3.add(new PointF[]{new PointF(f2, f10), new PointF(f2, f6), new PointF(f5, f6), new PointF(f5, f10)});
        arrayList3.add(new PointF[]{new PointF(f9, f10), new PointF(f9, f6), new PointF(f5, f6), new PointF(f5, f10)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList3));
        ArrayList arrayList4 = new ArrayList();
        arrayList4.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f5, f4), new PointF(f5, f7)});
        arrayList4.add(new PointF[]{new PointF(f5, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f5, f4)});
        arrayList4.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f10), new PointF(f5, f10), new PointF(f5, f4)});
        arrayList4.add(new PointF[]{new PointF(f5, f10), new PointF(f9, f10), new PointF(f9, f4), new PointF(f5, f4)});
        arrayList4.add(new PointF[]{new PointF(f2, f10), new PointF(f2, f6), new PointF(f5, f6), new PointF(f5, f10)});
        arrayList4.add(new PointF[]{new PointF(f9, f10), new PointF(f9, f6), new PointF(f5, f6), new PointF(f5, f10)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList4));
        ArrayList arrayList5 = new ArrayList();
        arrayList5.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f11, f4), new PointF(f11, f7)});
        arrayList5.add(new PointF[]{new PointF(f11, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f11, f4)});
        arrayList5.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f10), new PointF(f11, f10), new PointF(f11, f4)});
        arrayList5.add(new PointF[]{new PointF(f11, f10), new PointF(f9, f10), new PointF(f9, f4), new PointF(f11, f4)});
        arrayList5.add(new PointF[]{new PointF(f2, f10), new PointF(f2, f6), new PointF(f11, f6), new PointF(f11, f10)});
        arrayList5.add(new PointF[]{new PointF(f9, f10), new PointF(f9, f6), new PointF(f11, f6), new PointF(f11, f10)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList5));
        ArrayList arrayList6 = new ArrayList();
        arrayList6.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f8, f4), new PointF(f8, f7)});
        arrayList6.add(new PointF[]{new PointF(f8, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f8, f4)});
        arrayList6.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f10), new PointF(f5, f10), new PointF(f5, f4)});
        arrayList6.add(new PointF[]{new PointF(f5, f10), new PointF(f9, f10), new PointF(f9, f4), new PointF(f5, f4)});
        arrayList6.add(new PointF[]{new PointF(f2, f10), new PointF(f2, f6), new PointF(f8, f6), new PointF(f8, f10)});
        arrayList6.add(new PointF[]{new PointF(f9, f10), new PointF(f9, f6), new PointF(f8, f6), new PointF(f8, f10)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList6));
        ArrayList arrayList7 = new ArrayList();
        float f12 = f * 0.25f;
        arrayList7.add(new PointF[]{new PointF(f2, f10), new PointF(f12, f10), new PointF(f12, f6), new PointF(f2, f6)});
        arrayList7.add(new PointF[]{new PointF(f12, f10), new PointF(f11, f10), new PointF(f11, f6), new PointF(f12, f6)});
        arrayList7.add(new PointF[]{new PointF(f9, f6), new PointF(f11, f6), new PointF(f11, f4), new PointF(f9, f4)});
        arrayList7.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f10), new PointF(f11, f10), new PointF(f11, f7)});
        float f13 = f * 0.75f;
        arrayList7.add(new PointF[]{new PointF(f11, f7), new PointF(f13, f7), new PointF(f13, f4), new PointF(f11, f4)});
        arrayList7.add(new PointF[]{new PointF(f13, f7), new PointF(f9, f7), new PointF(f9, f4), new PointF(f13, f4)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList7));
        ArrayList arrayList8 = new ArrayList();
        arrayList8.add(new PointF[]{new PointF(f2, f10), new PointF(f5, f10), new PointF(f5, f6), new PointF(f2, f6)});
        arrayList8.add(new PointF[]{new PointF(f2, f4), new PointF(f5, f4), new PointF(f5, f10), new PointF(f2, f10)});
        arrayList8.add(new PointF[]{new PointF(f2, f7), new PointF(f5, f7), new PointF(f5, f4), new PointF(f2, f4)});
        float f14 = 0.4166667f * f3;
        arrayList8.add(new PointF[]{new PointF(f5, f6), new PointF(f8, f6), new PointF(f8, f14), new PointF(f5, f14)});
        arrayList8.add(new PointF[]{new PointF(f8, f6), new PointF(f9, f6), new PointF(f9, f14), new PointF(f8, f14)});
        arrayList8.add(new PointF[]{new PointF(f5, f7), new PointF(f9, f7), new PointF(f9, f14), new PointF(f5, f14)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList8));
        ArrayList arrayList9 = new ArrayList();
        float f15 = 0.5f * f3;
        arrayList9.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f15), new PointF(f5, f15), new PointF(f5, f7)});
        arrayList9.add(new PointF[]{new PointF(f2, f15), new PointF(f2, f6), new PointF(f5, f6), new PointF(f5, f15)});
        arrayList9.add(new PointF[]{new PointF(f5, f6), new PointF(f8, f6), new PointF(f8, f15), new PointF(f5, f15)});
        arrayList9.add(new PointF[]{new PointF(f5, f7), new PointF(f8, f7), new PointF(f8, f15), new PointF(f5, f15)});
        arrayList9.add(new PointF[]{new PointF(f8, f6), new PointF(f9, f6), new PointF(f9, f15), new PointF(f8, f15)});
        arrayList9.add(new PointF[]{new PointF(f9, f15), new PointF(f9, f7), new PointF(f8, f7), new PointF(f8, f15)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList9));
        ArrayList arrayList10 = new ArrayList();
        arrayList10.add(new PointF[]{new PointF(f2, f10), new PointF(f2, f6), new PointF(f5, f6), new PointF(f5, f10)});
        arrayList10.add(new PointF[]{new PointF(f5, f6), new PointF(f8, f6), new PointF(f8, f10), new PointF(f5, f10)});
        arrayList10.add(new PointF[]{new PointF(f8, f6), new PointF(f9, f6), new PointF(f9, f10), new PointF(f8, f10)});
        arrayList10.add(new PointF[]{new PointF(f9, f10), new PointF(f9, f4), new PointF(f8, f4), new PointF(f8, f10)});
        arrayList10.add(new PointF[]{new PointF(f8, f4), new PointF(f8, f7), new PointF(f9, f7), new PointF(f9, f4)});
        arrayList10.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f10), new PointF(f8, f10), new PointF(f8, f7)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList10));
        ArrayList arrayList11 = new ArrayList();
        float f16 = 0.25f * f3;
        arrayList11.add(new PointF[]{new PointF(f2, f6), new PointF(f8, f6), new PointF(f8, f16), new PointF(f2, f16)});
        arrayList11.add(new PointF[]{new PointF(f8, f6), new PointF(f9, f6), new PointF(f9, f16), new PointF(f8, f16)});
        arrayList11.add(new PointF[]{new PointF(f8, f16), new PointF(f8, f7), new PointF(f9, f7), new PointF(f9, f16)});
        arrayList11.add(new PointF[]{new PointF(f2, f15), new PointF(f2, f16), new PointF(f8, f16), new PointF(f8, f15)});
        float f17 = f3 * 0.75f;
        arrayList11.add(new PointF[]{new PointF(f2, f17), new PointF(f2, f15), new PointF(f8, f15), new PointF(f8, f17)});
        arrayList11.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f17), new PointF(f8, f17), new PointF(f8, f7)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList11));
        ArrayList arrayList12 = new ArrayList();
        arrayList12.add(new PointF[]{new PointF(f2, f6), new PointF(f9, f6), new PointF(f9, f16), new PointF(f2, f16)});
        arrayList12.add(new PointF[]{new PointF(f2, f15), new PointF(f2, f16), new PointF(f11, f16), new PointF(f11, f15)});
        arrayList12.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f17), new PointF(f9, f17), new PointF(f9, f7)});
        arrayList12.add(new PointF[]{new PointF(f2, f17), new PointF(f2, f15), new PointF(f11, f15), new PointF(f11, f17)});
        arrayList12.add(new PointF[]{new PointF(f11, f15), new PointF(f11, f16), new PointF(f9, f16), new PointF(f9, f15)});
        arrayList12.add(new PointF[]{new PointF(f11, f17), new PointF(f11, f15), new PointF(f9, f15), new PointF(f9, f17)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList12));
        ArrayList arrayList13 = new ArrayList();
        arrayList13.add(new PointF[]{new PointF(f2, f6), new PointF(f9, f6), new PointF(f9, f16), new PointF(f2, f16)});
        arrayList13.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f16), new PointF(f5, f16), new PointF(f5, f4)});
        arrayList13.add(new PointF[]{new PointF(f5, f4), new PointF(f8, f4), new PointF(f8, f16), new PointF(f5, f16)});
        arrayList13.add(new PointF[]{new PointF(f2, f7), new PointF(f2, f4), new PointF(f11, f4), new PointF(f11, f7)});
        arrayList13.add(new PointF[]{new PointF(f8, f4), new PointF(f8, f16), new PointF(f9, f16), new PointF(f9, f4)});
        arrayList13.add(new PointF[]{new PointF(f11, f7), new PointF(f11, f4), new PointF(f9, f4), new PointF(f9, f7)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList13));
    }
}
