package hdphoto.galleryimages.gelleryalbum.Images_android.Ibex_CollageModule.Luxgen_ShapeLayout;

import android.graphics.PointF;
import hdphoto.galleryimages.gelleryalbum.R;
import java.util.ArrayList;


public class Rabbit_ClgShape3 extends Spyker_CollageShapeUtils {
    public static int shapeCount = 3;

    public Rabbit_ClgShape3(int i, int i2) {
        this.collageLayoutList = new ArrayList();
        ArrayList arrayList = new ArrayList();
        float f = i;
        float f2 = f * 0.3333333f;
        float f3 = i2;
        float f4 = f3 * 1.0f;
        float f5 = f3 * 0.0f;
        float f6 = f * 0.6666667f;
        arrayList.add(new PointF[]{new PointF(f2, f4), new PointF(f2, f5), new PointF(f6, f5), new PointF(f6, f4)});
        float f7 = 0.0f * f;
        arrayList.add(new PointF[]{new PointF(f7, f4), new PointF(f2, f4), new PointF(f2, f5), new PointF(f7, f5)});
        float f8 = 1.0f * f;
        arrayList.add(new PointF[]{new PointF(f6, f4), new PointF(f8, f4), new PointF(f8, f5), new PointF(f6, f5)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList));
        ArrayList arrayList2 = new ArrayList();
        float f9 = f3 * 0.5f;
        arrayList2.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f9), new PointF(f8, f9), new PointF(f8, f5)});
        arrayList2.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f4), new PointF(f8, f4), new PointF(f8, f9)});
        float f10 = f * 0.2f;
        float f11 = 0.2f * f3;
        float f12 = f3 * 0.8f;
        float f13 = f * 0.8f;
        arrayList2.add(new PointF[]{new PointF(f10, f11), new PointF(f10, f12), new PointF(f13, f12), new PointF(f13, f11)});
        Rabbit_CollageLayout cMCollageLayout = new Rabbit_CollageLayout(arrayList2);
        cMCollageLayout.maskPairList.add(new Spyker_MaskPair(2, R.drawable.mask_circle));
        cMCollageLayout.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout);
        ArrayList arrayList3 = new ArrayList();
        float f14 = 0.58f * f;
        arrayList3.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f9), new PointF(f14, f9), new PointF(f14, f5)});
        arrayList3.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f4), new PointF(f14, f4), new PointF(f14, f9)});
        float f15 = 0.42f * f;
        float f16 = f3 * 0.25f;
        float f17 = f3 * 0.75f;
        arrayList3.add(new PointF[]{new PointF(f15, f16), new PointF(f15, f17), new PointF(f8, f17), new PointF(f8, f16)});
        Rabbit_CollageLayout cMCollageLayout2 = new Rabbit_CollageLayout(arrayList3);
        cMCollageLayout2.maskPairList.add(new Spyker_MaskPair(0, R.drawable.mask_hexagon));
        cMCollageLayout2.maskPairList.add(new Spyker_MaskPair(1, R.drawable.mask_hexagon));
        cMCollageLayout2.maskPairList.add(new Spyker_MaskPair(2, R.drawable.mask_hexagon));
        this.collageLayoutList.add(cMCollageLayout2);
        ArrayList arrayList4 = new ArrayList();
        float f18 = 0.5f * f;
        arrayList4.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f5)});
        arrayList4.add(new PointF[]{new PointF(f18, f5), new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f5)});
        arrayList4.add(new PointF[]{new PointF(f * 0.25f, f9), new PointF(f18, f17), new PointF(f * 0.75f, f9), new PointF(f18, f16)});
        Rabbit_CollageLayout cMCollageLayout3 = new Rabbit_CollageLayout(arrayList4);
        cMCollageLayout3.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout3);
        ArrayList arrayList5 = new ArrayList();
        arrayList5.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f9), new PointF(f8, f9), new PointF(f8, f5)});
        arrayList5.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f4), new PointF(f8, f4), new PointF(f8, f9)});
        arrayList5.add(new PointF[]{new PointF(f10, f11), new PointF(f10, f12), new PointF(f13, f12), new PointF(f13, f11)});
        Rabbit_CollageLayout cMCollageLayout4 = new Rabbit_CollageLayout(arrayList5);
        cMCollageLayout4.maskPairList.add(new Spyker_MaskPair(2, R.drawable.mask_heart));
        cMCollageLayout4.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout4);
        ArrayList arrayList6 = new ArrayList();
        arrayList6.add(new PointF[]{new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f5), new PointF(f18, f5)});
        arrayList6.add(new PointF[]{new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f9), new PointF(f7, f9)});
        arrayList6.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f5), new PointF(f18, f5), new PointF(f18, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList6));
        ArrayList arrayList7 = new ArrayList();
        arrayList7.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f5)});
        arrayList7.add(new PointF[]{new PointF(f18, f5), new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f5)});
        arrayList7.add(new PointF[]{new PointF(f10, f11), new PointF(f10, f12), new PointF(f13, f12), new PointF(f13, f11)});
        Rabbit_CollageLayout cMCollageLayout5 = new Rabbit_CollageLayout(arrayList7);
        cMCollageLayout5.maskPairList.add(new Spyker_MaskPair(2, R.drawable.mask_hexagon));
        cMCollageLayout5.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout5);
        ArrayList arrayList8 = new ArrayList();
        arrayList8.add(new PointF[]{new PointF(f2, f4), new PointF(f8, f4), new PointF(f8, f5), new PointF(f2, f5)});
        arrayList8.add(new PointF[]{new PointF(f7, f4), new PointF(f2, f4), new PointF(f2, f9), new PointF(f7, f9)});
        arrayList8.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f5), new PointF(f2, f5), new PointF(f2, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList8));
        ArrayList arrayList9 = new ArrayList();
        arrayList9.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f5)});
        arrayList9.add(new PointF[]{new PointF(f18, f5), new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f5)});
        arrayList9.add(new PointF[]{new PointF(f10, f11), new PointF(f10, f12), new PointF(f13, f12), new PointF(f13, f11)});
        Rabbit_CollageLayout cMCollageLayout6 = new Rabbit_CollageLayout(arrayList9);
        cMCollageLayout6.maskPairList.add(new Spyker_MaskPair(2, R.drawable.mask_circle));
        cMCollageLayout6.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout6);
        ArrayList arrayList10 = new ArrayList();
        arrayList10.add(new PointF[]{new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f5), new PointF(f18, f5)});
        float f19 = 0.6666667f * f3;
        arrayList10.add(new PointF[]{new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f19), new PointF(f7, f19)});
        arrayList10.add(new PointF[]{new PointF(f7, f19), new PointF(f7, f5), new PointF(f18, f5), new PointF(f18, f19)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList10));
        ArrayList arrayList11 = new ArrayList();
        arrayList11.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f9), new PointF(f8, f9), new PointF(f8, f5)});
        arrayList11.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f4), new PointF(f8, f4), new PointF(f8, f9)});
        arrayList11.add(new PointF[]{new PointF(f10, f16), new PointF(f10, f17), new PointF(f13, f17), new PointF(f13, f16)});
        Rabbit_CollageLayout cMCollageLayout7 = new Rabbit_CollageLayout(arrayList11);
        cMCollageLayout7.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout7);
        ArrayList arrayList12 = new ArrayList();
        arrayList12.add(new PointF[]{new PointF(f6, f4), new PointF(f8, f4), new PointF(f8, f5), new PointF(f6, f5)});
        arrayList12.add(new PointF[]{new PointF(f7, f4), new PointF(f6, f4), new PointF(f6, f9), new PointF(f7, f9)});
        arrayList12.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f5), new PointF(f6, f5), new PointF(f6, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList12));
        ArrayList arrayList13 = new ArrayList();
        arrayList13.add(new PointF[]{new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f5), new PointF(f7, f5)});
        arrayList13.add(new PointF[]{new PointF(f18, f5), new PointF(f18, f9), new PointF(f8, f9), new PointF(f8, f5)});
        arrayList13.add(new PointF[]{new PointF(f18, f9), new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList13));
        ArrayList arrayList14 = new ArrayList();
        arrayList14.add(new PointF[]{new PointF(f7, f5), new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f5)});
        arrayList14.add(new PointF[]{new PointF(f18, f5), new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f5)});
        arrayList14.add(new PointF[]{new PointF(f10, f16), new PointF(f10, f17), new PointF(f13, f17), new PointF(f13, f16)});
        Rabbit_CollageLayout cMCollageLayout8 = new Rabbit_CollageLayout(arrayList14);
        cMCollageLayout8.setClearIndex(2);
        this.collageLayoutList.add(cMCollageLayout8);
        ArrayList arrayList15 = new ArrayList();
        arrayList15.add(new PointF[]{new PointF(f7, f4), new PointF(f2, f4), new PointF(f2, f5), new PointF(f7, f5)});
        arrayList15.add(new PointF[]{new PointF(f2, f5), new PointF(f2, f9), new PointF(f8, f9), new PointF(f8, f5)});
        arrayList15.add(new PointF[]{new PointF(f2, f9), new PointF(f2, f4), new PointF(f8, f4), new PointF(f8, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList15));
        ArrayList arrayList16 = new ArrayList();
        arrayList16.add(new PointF[]{new PointF(f7, f4), new PointF(f6, f4), new PointF(f6, f5), new PointF(f7, f5)});
        arrayList16.add(new PointF[]{new PointF(f6, f5), new PointF(f6, f9), new PointF(f8, f9), new PointF(f8, f5)});
        arrayList16.add(new PointF[]{new PointF(f6, f9), new PointF(f6, f4), new PointF(f8, f4), new PointF(f8, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList16));
        ArrayList arrayList17 = new ArrayList();
        float f20 = f3 * 0.3333333f;
        arrayList17.add(new PointF[]{new PointF(f7, f20), new PointF(f8, f20), new PointF(f8, f5), new PointF(f7, f5)});
        arrayList17.add(new PointF[]{new PointF(f7, f19), new PointF(f7, f20), new PointF(f8, f20), new PointF(f8, f19)});
        arrayList17.add(new PointF[]{new PointF(f7, f4), new PointF(f7, f19), new PointF(f8, f19), new PointF(f8, f4)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList17));
        ArrayList arrayList18 = new ArrayList();
        arrayList18.add(new PointF[]{new PointF(f7, f20), new PointF(f8, f20), new PointF(f8, f5), new PointF(f7, f5)});
        arrayList18.add(new PointF[]{new PointF(f7, f4), new PointF(f18, f4), new PointF(f18, f20), new PointF(f7, f20)});
        arrayList18.add(new PointF[]{new PointF(f18, f4), new PointF(f8, f4), new PointF(f8, f20), new PointF(f18, f20)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList18));
        ArrayList arrayList19 = new ArrayList();
        arrayList19.add(new PointF[]{new PointF(f7, f4), new PointF(f8, f4), new PointF(f8, f9), new PointF(f7, f9)});
        arrayList19.add(new PointF[]{new PointF(f7, f9), new PointF(f7, f5), new PointF(f18, f5), new PointF(f18, f9)});
        arrayList19.add(new PointF[]{new PointF(f18, f5), new PointF(f8, f5), new PointF(f8, f9), new PointF(f18, f9)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList19));
        ArrayList arrayList20 = new ArrayList();
        arrayList20.add(new PointF[]{new PointF(f7, f16), new PointF(f8, f16), new PointF(f8, f5), new PointF(f7, f5)});
        arrayList20.add(new PointF[]{new PointF(f7, f17), new PointF(f7, f16), new PointF(f8, f16), new PointF(f8, f17)});
        arrayList20.add(new PointF[]{new PointF(f7, f4), new PointF(f7, f17), new PointF(f8, f17), new PointF(f8, f4)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList20));
        ArrayList arrayList21 = new ArrayList();
        arrayList21.add(new PointF[]{new PointF(f7, f4), new PointF(f8, f4), new PointF(f8, f19), new PointF(f7, f19)});
        arrayList21.add(new PointF[]{new PointF(f7, f19), new PointF(f7, f5), new PointF(f18, f5), new PointF(f18, f19)});
        arrayList21.add(new PointF[]{new PointF(f18, f5), new PointF(f8, f5), new PointF(f8, f19), new PointF(f18, f19)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList21));
        ArrayList arrayList22 = new ArrayList();
        arrayList22.add(new PointF[]{new PointF(f7, f4), new PointF(f8, f4), new PointF(f8, f20), new PointF(f7, f20)});
        arrayList22.add(new PointF[]{new PointF(f7, f20), new PointF(f7, f5), new PointF(f18, f5), new PointF(f18, f20)});
        arrayList22.add(new PointF[]{new PointF(f18, f5), new PointF(f8, f5), new PointF(f8, f20), new PointF(f18, f20)});
        this.collageLayoutList.add(new Rabbit_CollageLayout(arrayList22));
    }
}
